# Generated by Django 2.0.7 on 2018-10-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_auto_20181011_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'CANADA'), ('FR', 'FRANCE'), ('DE', 'GERMANY'), ('IT', 'ITALY'), ('SP', 'SPAIN'), ('UK', 'UNITED KINDOM'), ('USA', 'UNITED STATES OF AMERICA')], default='7', max_length=1, verbose_name='Country'),
        ),
    ]
