# Generated by Django 2.0.7 on 2018-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0012_auto_20181012_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'CANADA'), ('FR', 'FRANCE'), ('DE', 'GERMANY'), ('IT', 'ITALY'), ('SP', 'SPAIN'), ('UK', 'UNITED_KINDOM'), ('USA', 'UNITED_STATES')], default='USA', max_length=10, verbose_name='Country'),
        ),
    ]
