# Generated by Django 2.0.7 on 2018-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0016_auto_20181012_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('UK', 'United Kingdom'), ('USA', 'United States')], default='USA', max_length=20, verbose_name='Country'),
        ),
    ]
