# Generated by Django 2.0.7 on 2018-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0017_auto_20181029_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('UK', 'United Kingdom'), ('USA', 'United States')], default='USA', max_length=20, verbose_name='Country'),
        ),
    ]
