# Generated by Django 2.0.7 on 2018-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0018_auto_20181119_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('GB', 'United Kingdom'), ('US', 'United States')], default='USA', max_length=20, verbose_name='Country'),
        ),
    ]
