# Generated by Django 2.0.7 on 2018-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0019_auto_20181119_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('GB', 'United Kingdom'), ('US', 'United States')], default='US', max_length=20, verbose_name='Country'),
        ),
    ]
