# Generated by Django 2.0.7 on 2018-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0021_auto_20181119_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_ean',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Ebay Product EAN'),
        ),
    ]
