# Generated by Django 2.1.2 on 2019-03-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0022_product_ebay_ean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='seller_ids',
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True, verbose_name='Keywords'),
        ),
    ]
