# Generated by Django 2.1.2 on 2019-04-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0023_auto_20190331_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='asin_file',
        ),
        migrations.RemoveField(
            model_name='job',
            name='asin_codes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='asin_results_counter',
        ),
        migrations.RemoveField(
            model_name='job',
            name='asin_status',
        ),
        migrations.AddField(
            model_name='file',
            name='search_file',
            field=models.BooleanField(default=False, verbose_name='Search File'),
        ),
        migrations.AddField(
            model_name='job',
            name='keylist',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True, verbose_name='Key List'),
        ),
        migrations.AddField(
            model_name='job',
            name='search_results_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Search Results Count'),
        ),
        migrations.AddField(
            model_name='job',
            name='search_status',
            field=models.BooleanField(default=False, verbose_name='Search Status'),
        ),
    ]
