# Generated by Django 2.1.2 on 2019-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0025_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amazon_asin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_bread_crumbs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_is_addon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_is_prime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_item_model_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_product_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_review_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_sold_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_bread_crumbs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_ean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_mpn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_review_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_sold_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_ssn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_upc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_url',
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='bread_crumbs',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Bread Crumbs'),
        ),
        migrations.AddField(
            model_name='product',
            name='bsr',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='BSR'),
        ),
        migrations.AddField(
            model_name='product',
            name='bsr_category',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='BSR Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='competition',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Competition'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpc',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='CPC'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature1',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Feature 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature2',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Feature 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature3',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Feature 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature4',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Feature 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature5',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Feature 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='five_star_percentage',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Five Star Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='four_star_percentage',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Four Star Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='image7',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Image 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='In Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_addon',
            field=models.BooleanField(default=False, verbose_name='Is Addon'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_amz',
            field=models.BooleanField(default=False, verbose_name='Is AMZ'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fba',
            field=models.BooleanField(default=False, verbose_name='Is FBA'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fbm',
            field=models.BooleanField(default=False, verbose_name='Is FBM'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_prime',
            field=models.BooleanField(default=False, verbose_name='Is Prime'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_dimensions_length',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Item Dimensions Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_dimensions_thickness',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Item Dimensions Thickness'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_dimensions_width',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Item Dimensions Width'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_model_number',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Item Model Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_weight',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Item Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='monthly_search_volume',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Monthly Search Volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='one_star_percentage',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='One Star Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Review Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_score',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Review Score'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_keyword',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Search Keyword'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_rank',
            field=models.BooleanField(default=False, verbose_name='Search Rank'),
        ),
        migrations.AddField(
            model_name='product',
            name='sellers_count',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Sellers Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Sold By'),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsored',
            field=models.BooleanField(default=False, verbose_name='Is Sponsored'),
        ),
        migrations.AddField(
            model_name='product',
            name='three_star_percentage',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Three Star Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='two_star_percentage',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Two Star Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
