# Generated by Django 2.1.2 on 2019-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0026_auto_20190401_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Search Rank'),
        ),
    ]
